fix(icons): fix star and star filled svg
magnetis/astro-native pull request #386
Opened 2021-12-07 22:48 UTC by julianosbento

# What

Fix star and star filled icons box layout

# Why

The icons wasn't centralized

# How

- Fix icon box on figma, re-exported svg and implemented on app

# Sample

N/A

# QA

This will reflect directly when the icon will be applied at any context

2021-12-07 23:12 UTC, LopesAlysson requested changes

2021-12-07 23:12 UTC, LopesAlysson commented on src/components/Icons/Support/Star.tsx
> +
Acredito que isso não deveria estar aqui 👀

2021-12-07 23:20 UTC, julianosbento commented on src/components/Icons/Support/Star.tsx
> +
Fixed, but I pushed force with amend

2021-12-08 17:08 UTC, LopesAlysson approved these changes

2021-12-08 18:03 UTC, albertozaranza approved these changes

2021-12-08 18:04 UTC, merged