feat(Title): Implement Title component
magnetis/astro-native pull request #43
Opened 2020-12-23 20:19 UTC by renatofreire

# What

Add Title component

# Why

Title component was the last missing typography

2020-12-23 20:34 UTC, pedro-cerdera submitted a review, later dismissed

2020-12-23 20:39 UTC, victorheringer approved these changes
LGTM

2020-12-23 20:48 UTC, LopesAlysson requested changes

2020-12-23 20:48 UTC, LopesAlysson commented on src/components/Text/Title.tsx
> +import { BaseTextProps } from './types';
```suggestion
import type { BaseTextProps } from './types';
```

2020-12-23 20:48 UTC, LopesAlysson commented on src/components/Text/Title.tsx
> +}: BaseTextProps & { fontSize: number; bold: boolean }) {
Is it possible to have a non-bold Title?

2020-12-28 12:52 UTC, renatofreire commented on src/components/Text/Title.tsx
> +    fontFamily: poppinsSemiBold,
@LopesAlysson good point. Actually, all titles are semibold.
I fixed it and remove the unnecessary prop :)

2020-12-28 13:33 UTC, LopesAlysson approved these changes
:shipit:

2020-12-28 14:44 UTC, merged