Fix link component
magnetis/astro-native pull request #50
Opened 2021-01-13 19:47 UTC by julianosbento

# What
- Fix link component

# Why
- The component was aligned vertically when nested inside another `Text` component

# How
- Removed `Pressable` wrapper

# Sample
| With Pressable | Without Pressable |
| ------------- |-------------| 
| <img src="https://user-images.githubusercontent.com/13890272/104501565-a8daf080-55be-11eb-99e5-3a3882a26b08.png" height="80" width="250" /> | <img src="https://user-images.githubusercontent.com/13890272/104501567-a9738700-55be-11eb-97f5-0c843a4012ef.png" height="80" width="250" /> |

[CH54268](https://app.clubhouse.io/magnetis/story/54268/corrigir-alinhamento-vertical-de-links-aninhados-em-componentes-de-texto)

2021-01-14 12:53 UTC, LopesAlysson commented on src/components/Buttons/Link.tsx
> +    : null;
Is it safe to leave an onPress event to a TextComponent to handle? I miss hitSlop here. Please bear in mind that all elements must have a minimum 48px touch area.

2021-01-26 21:31 UTC, julianosbento commented on src/components/Buttons/Link.tsx
> +    : null;
The problem is that `TouchableOpacity`, `TouchableHighlight` and `Pressable`, break the layout.
I tried to apply `TouchableWithoutFeedback` wrapping, it's gonna right, but the `hitSlop` didn't make any effect.
So, I think that the best way, is follow without wrapping the component.

2021-01-27 12:39 UTC, pedro-cerdera submitted a review, later dismissed

2021-02-09 18:49 UTC, LopesAlysson approved these changes

2021-02-09 18:50 UTC, LopesAlysson reviewed
Just a thing: it's misleading to call this PR a fix when it has the feature to change color link.
Also, the commit pattern is not following conventional commit from our [guide](https://github.com/magnetis/astro-native/blob/main/.github/CONTRIBUTING.md#commit-messages)

2021-02-09 18:51 UTC, LopesAlysson requested changes
Just because of the commit messages

2021-02-09 20:48 UTC, LopesAlysson requested changes

2021-02-09 20:48 UTC, LopesAlysson commented on src/components/Buttons/Link.tsx
> +  color?: ButtonColor;
Stil bothers me that the commit mentions a fix, but a feature is being introduced.
This could make our changelog give wrong informations.

I think it is better to split this commit in two: one for the fix and another for the new color feature.

2021-02-19 14:44 UTC, LopesAlysson requested changes
I believe this commmit (0abd84e7a56f0aa06419b3e93646f1eff1fe9798) should be a feature commit, hence a new behavior is being added.

Refactor commits doesn't chenge the way the API functions.

Again, we have to be very careful about commit messages, since it will be our changelog doc.

2021-02-19 20:11 UTC, LopesAlysson submitted a review, later dismissed

2021-02-19 21:29 UTC, LopesAlysson approved these changes

2021-02-19 21:29 UTC, merged