Feature/tabs border bottom
magnetis/astro-native pull request #52
Opened 2021-01-26 22:03 UTC by carlosberti

# What

Add borderBottom option to tabs component

# Why

We need to add this option to be like the spec on figma

# How

Changing the tabs component in order to add borderBottom option

# Sample

![image](https://user-images.githubusercontent.com/22118601/105911612-1e0be400-6009-11eb-8a0e-abd23e0abaa2.png)

2021-01-27 14:09 UTC, LopesAlysson requested changes
I'm a bit worried with the coverage drop after this feature. What's not being tested?
Can you check in the coverage report?

2021-01-27 14:09 UTC, LopesAlysson commented on src/components/ControlsToggles/Tabs.tsx
>    activeItemColor,
Since this prop is now optional, we have to initialize it with some value

2021-01-27 14:09 UTC, LopesAlysson commented on src/components/ControlsToggles/Tabs.tsx
> +              },
I think we should add these styles in the Stylesheet object as `itemWithBorderBottom` or something;

2021-01-27 14:09 UTC, LopesAlysson commented on src/components/ControlsToggles/stories/Tabs.story.tsx
> +storiesOf('Controls & Toggles', module)
For more than one story, we should follow the pattern used in other components like PrimaryText.

```
controlsTogglesStories = storiesOf('Controls & Toggles', module);

controlsTogglesStories.add('Tabs',  () => {
[...]
```

Just to avoid unnecessary chaining.

2021-01-27 17:22 UTC, carlosberti commented
> I'm a bit worried with the coverage drop after this feature. What's not being tested?
> Can you check in the coverage report?

I will check it

2021-01-27 17:29 UTC, carlosberti commented on src/components/ControlsToggles/Tabs.tsx
> +              },
I don't know if it is the best approach once those styles are being used by tabs without border bottom as well

2021-01-27 18:12 UTC, LopesAlysson commented on src/components/ControlsToggles/Tabs.tsx
> +              },
The order that we put an array of styles object matters in the way that styles will be applied. 
We can just restore the original style and add this third `itemWithBorderBottom` conditionally.

2021-01-27 18:15 UTC, carlosberti commented on src/components/ControlsToggles/Tabs.tsx
> +              },
Hummmm, okay. I will change it

2021-01-28 12:28 UTC, LopesAlysson commented on src/components/ControlsToggles/Tabs.tsx
> +  activeItemColor = 'transparent',
I don't think this is a good  default value, hence if tabs has background and active color as transparent, it will be invisible 😟

2021-01-28 12:28 UTC, LopesAlysson commented on src/components/ControlsToggles/Tabs.tsx
> +  borderBottom,
I think it's a good idea to initialize that prop as false, just to avoid handling *undefined* values.

2021-01-28 12:28 UTC, LopesAlysson commented on src/components/ControlsToggles/Tabs.tsx
> +
I really think we should take advantage of how performatic `Stylesheets.create` are in that case. Saving it in a constant will demand recalculation on every render. Since the only dynamic value here is the borderBottomColor, we can do similar to non borderBottom tabs.

2021-01-29 20:00 UTC, LopesAlysson approved these changes
LGTM!

2021-02-01 18:30 UTC, merged