Iconography: arrows
magnetis/astro-native pull request #538
Opened 2022-04-21 15:05 UTC by Michele-Camargo

# What

Implement the new icons proposed in the [Iconography](https://www.figma.com/file/9WVVk8Vobz2ZMzmHjtEFEh/Iconography?node-id=0%3A322) spec

# Why

Enable us to have a greater visual collection, once we have a greater and more diverse amount of icons

# How

- Added arrows components in `/components/Icons`

# Sample

https://user-images.githubusercontent.com/44146877/164487771-ec30f6be-eae5-4114-8e7a-f49d82c191cf.mov

# QA

2022-04-21 21:12 UTC, lucianomlima commented on jest.config.js
> +    '!src/components/Icons/Arrows/**/*.{ts,tsx}',
❓ Can you help me understand why these new icons need a new directory?
I think that can be placed in the Support directory because we already have some arrow incons there.

2022-04-21 21:12 UTC, lucianomlima commented on src/components/Icons/index.ts
> +// export * from './Arrows';
❓ Is this comment line right?

2022-04-21 21:12 UTC, lucianomlima commented on src/components/Buttons/__tests__/utils.test.tsx
> +import { ArrowUpIcon } from '@components/Icons';
❓ Because [this comment](https://github.com/magnetis/astro-native/pull/538/files#diff-d42fdb3eb807e96a46cf38f3fcf9506f806ea247aaa37bf8edba99bb03c8a2e9R3), you are importing ArrowUpIcon from Support directory. Is this the expected behavior?

2022-04-21 21:12 UTC, lucianomlima commented on src/components/Icons/Arrows/ArrowChevronDoubleDown.tsx
> +  height = 24,
🔧 All icon components that we already have in this package uses 32 in both `width` and `height`. These new icons should follow the same sizes to avoid wrong rendering when in use.

This difference can causes misalign between icons when placed side by side or onr above the other.

2022-04-25 13:24 UTC, Michele-Camargo commented on src/components/Icons/index.ts
> +// export * from './Arrows';
Yes, this line is a comment because it has some icons in support with the same name, it was throwing error already [card](https://produtomagnetis.atlassian.net/jira/software/projects/CON/boards/86?selectedIssue=CON-224) to fix it

2022-04-25 13:32 UTC, Michele-Camargo commented on src/components/Buttons/__tests__/utils.test.tsx
> +import { ArrowUpIcon } from '@components/Icons';
I'm importing the ArrowUpIcon because the "support" and "dashboard" directories will be deleted, and the AlertIcon will disappear

2022-04-25 13:35 UTC, Michele-Camargo commented on src/components/Icons/Arrows/ArrowChevronDoubleDown.tsx
> +  height = 24,
i am follow the [spec](https://www.figma.com/file/9WVVk8Vobz2ZMzmHjtEFEh/Iconography?node-id=1825%3A1490), which is right?

<img width="337" alt="image" src="https://user-images.githubusercontent.com/44146877/165099748-26536660-9f02-4747-b4ea-3559eb607d57.png">

2022-04-25 14:22 UTC, julianosbento requested changes
🔧 In all places that you define the `height` and `width` of the icon, needs to use `@magnetis/astro-tokens`, following the rule:
- borders: For border width
- radius: For border radius
- size: For height, margin, padding, width, etc ...

```typescript
width = sizes.smaller,
height = sizes.smaller,
```

2022-04-25 15:33 UTC, lucianomlima commented on jest.config.js
> +    '!src/components/Icons/Arrows/**/*.{ts,tsx}',
Ok, understand. Will be helpful if this PR have the Jira card link to check spec 😉

2022-04-25 15:36 UTC, lucianomlima commented on src/components/Buttons/__tests__/utils.test.tsx
> +import { ArrowUpIcon } from '@components/Icons';
So, you should change when remove it no? Right now, it's not need to change because both directories are not removed yet.

2022-04-25 15:42 UTC, lucianomlima commented on src/components/Icons/Arrows/ArrowChevronDoubleDown.tsx
> +  height = 24,
It's more safe we use the old value because we didn't have the guarantee that 24 is a value that not causes issues on our app. I suggest you finish all icon related cards first with the current icon size, and after this, test our app with 24 sized icons to know the effort and time to maybe adjust all issues related with this size change in the entire app.

This can be a very big task because will be required to validate this in all screens and in all components.
This way, we can move to the new icons first e fix all issues later.

2022-04-25 18:54 UTC, Michele-Camargo commented on src/components/Icons/Arrows/ArrowChevronDoubleLeft.tsx
> +  height = 24,
what about the viewbox? we will use `size.small` too?

2022-04-25 19:57 UTC, lucianomlima commented on src/components/Icons/Arrows/ArrowChevronDoubleLeft.tsx
> +  height = 24,
Yes!

2022-04-25 19:58 UTC, lucianomlima commented on src/components/Icons/Arrows/ArrowChevronDoubleDown.tsx
> +  height = 24,
I mark as resolved after understand that this PR only refers to astro-native@next

2022-04-25 19:59 UTC, lucianomlima commented on src/components/Buttons/__tests__/utils.test.tsx
> +import { ArrowUpIcon } from '@components/Icons';
This is not a request, so can be this way 😉

2022-04-25 20:32 UTC, albertozaranza approved these changes

2022-04-25 20:32 UTC, albertozaranza commented on src/components/Icons/Arrows/ArrowChevronDoubleDown.tsx
> +import { getFill } from '../utils';
:wrench: You can organize these imports

```suggestion
import React from 'react';
import { Path } from 'react-native-svg';
import { colors } from '@magnetis/astro-galaxy-tokens';

import BaseIcon from '../BaseIcon';
import { getFill } from '../utils';

import type { IconProps } from '../types';
```

2022-04-25 20:32 UTC, albertozaranza commented on src/components/Icons/Arrows/ArrowUpCircle.tsx
> +  id = 'ArrowUpCircletIcon',
:wrench:

```suggestion
  id = 'ArrowUpCircleIcon',
```

2022-04-25 20:32 UTC, albertozaranza commented on src/components/Icons/Arrows/ArrowChevronDoubleUp.tsx
> +  id = 'ArrowChevronDoubleUptIcon',
:wrench:

```suggestion
  id = 'ArrowChevronDoubleUpIcon',
```

2022-04-25 20:32 UTC, albertozaranza commented on src/components/Icons/Arrows/ArrowDownCircle.tsx
> +  id = 'ArrowDownCircletIcon',
:wrench:

```suggestion
  id = 'ArrowDownCircleIcon',
```

2022-04-25 20:32 UTC, albertozaranza commented on src/components/Icons/Arrows/ArrowLeftCircle.tsx
> +  id = 'ArrowLeftCircletIcon',
:wrench:

```suggestion
  id = 'ArrowLeftCircleIcon',
```

2022-04-25 20:32 UTC, albertozaranza commented on src/components/Icons/Arrows/ArrowRightCircle.tsx
> +  id = 'ArrowRightCircletIcon',
:wrench:

```suggestion
  id = 'ArrowRightCircleIcon',
```

2022-04-25 20:33 UTC, LopesAlysson commented on src/components/Icons/Arrows/ArrowChevronDoubleDown.tsx
> +    <BaseIcon id={id} color={color} width={width} height={height} viewBox={viewBox} {...props}>
If I can recall, we were using a `size` prop since all icons had same height and width. I'm not sure about that though.

2022-04-25 20:33 UTC, LopesAlysson commented on src/components/Icons/Arrows/ArrowChevronDoubleDown.tsx
> +import { IconProps } from '../types';
💅🏾 
```suggestion
import type { IconProps } from '../types';
```

2022-04-25 20:33 UTC, LopesAlysson commented on src/components/Icons/Arrows/ArrowChevronDoubleUp.tsx
> +  id = 'ArrowChevronDoubleUptIcon',
Shouldn't it be `ArrowChevronDoubleUpIcon` ?
```suggestion
  id = 'ArrowChevronDoubleUpIcon',
```

2022-04-25 20:33 UTC, LopesAlysson commented on src/components/Icons/Arrows/ArrowDownCircle.tsx
> +  id = 'ArrowDownCircletIcon',
💅🏾 
```suggestion
  id = 'ArrowDownCircleIcon',
```

2022-04-25 20:33 UTC, LopesAlysson commented on src/components/Icons/Arrows/ArrowLeftCircle.tsx
> +  id = 'ArrowLeftCircletIcon',
💅🏾 

```suggestion
  id = 'ArrowLeftCircleIcon',
```

2022-04-25 20:33 UTC, LopesAlysson commented on src/components/Icons/Arrows/ArrowRightCircle.tsx
> +  id = 'ArrowRightCircletIcon',
💅🏾 

```suggestion
  id = 'ArrowRightCircleIcon',
```

2022-04-25 20:33 UTC, LopesAlysson commented on src/components/Icons/Arrows/ArrowUpCircle.tsx
> +  id = 'ArrowUpCircletIcon',
💅🏾 

```suggestion
  id = 'ArrowUpCircleIcon',
```

2022-04-25 20:33 UTC, matheussilva2 approved these changes

2022-04-28 16:41 UTC, lucianomlima commented on src/components/Icons/utils.ts
> +}
⛏️ I think the best way to define these properties is limit it to our size tokens instead of allow any size.
Using our size tokens will guarantee that, wherever used, will be consistent with our design system sizes.

2022-04-28 18:18 UTC, Michele-Camargo commented on src/components/Icons/utils.ts
> +}
I agree, but what is the best way to do this?
the idea was to use the token in the function call

2022-04-28 18:52 UTC, Michele-Camargo commented on src/components/Icons/Arrows/ArrowChevronDoubleLeft.tsx
> +  height = 24,
comment resolved in https://github.com/magnetis/astro-native/pull/538/commits/c88d626f3df6d91b787089916a173d70b2b52cce

2022-04-28 18:52 UTC, Michele-Camargo commented on src/components/Icons/Arrows/ArrowUpCircle.tsx
> +  id = 'ArrowUpCircletIcon',
comment resolved in https://github.com/magnetis/astro-native/pull/538/commits/c88d626f3df6d91b787089916a173d70b2b52cce

2022-04-28 18:52 UTC, Michele-Camargo commented on src/components/Icons/Arrows/ArrowChevronDoubleUp.tsx
> +  id = 'ArrowChevronDoubleUptIcon',
comment resolved in https://github.com/magnetis/astro-native/pull/538/commits/c88d626f3df6d91b787089916a173d70b2b52cce

2022-04-28 18:53 UTC, Michele-Camargo commented on src/components/Icons/Arrows/ArrowDownCircle.tsx
> +  id = 'ArrowDownCircletIcon',
comment resolved in https://github.com/magnetis/astro-native/pull/538/commits/c88d626f3df6d91b787089916a173d70b2b52cce

2022-04-28 18:53 UTC, Michele-Camargo commented on src/components/Icons/Arrows/ArrowLeftCircle.tsx
> +  id = 'ArrowLeftCircletIcon',
comment resolved in https://github.com/magnetis/astro-native/pull/538/commits/c88d626f3df6d91b787089916a173d70b2b52cce

2022-04-28 18:53 UTC, Michele-Camargo commented on src/components/Icons/Arrows/ArrowUpCircle.tsx
> +  id = 'ArrowUpCircletIcon',
comment resolved in https://github.com/magnetis/astro-native/pull/538/commits/c88d626f3df6d91b787089916a173d70b2b52cce

2022-04-28 18:53 UTC, Michele-Camargo commented on src/components/Icons/Arrows/ArrowChevronDoubleDown.tsx
> +import { IconProps } from '../types';
comment resolved in https://github.com/magnetis/astro-native/pull/538/commits/c88d626f3df6d91b787089916a173d70b2b52cce

2022-04-28 18:53 UTC, Michele-Camargo commented on src/components/Icons/Arrows/ArrowChevronDoubleUp.tsx
> +  id = 'ArrowChevronDoubleUptIcon',
comment resolved in https://github.com/magnetis/astro-native/pull/538/commits/c88d626f3df6d91b787089916a173d70b2b52cce

2022-04-28 18:54 UTC, Michele-Camargo commented on src/components/Icons/Arrows/ArrowDownCircle.tsx
> +  id = 'ArrowDownCircletIcon',
comment resolved in https://github.com/magnetis/astro-native/pull/538/commits/c88d626f3df6d91b787089916a173d70b2b52cce

2022-04-28 18:54 UTC, Michele-Camargo commented on src/components/Icons/Arrows/ArrowLeftCircle.tsx
> +  id = 'ArrowLeftCircletIcon',
comment resolved in https://github.com/magnetis/astro-native/pull/538/commits/c88d626f3df6d91b787089916a173d70b2b52cce

2022-04-28 18:54 UTC, Michele-Camargo commented on src/components/Icons/Arrows/ArrowRightCircle.tsx
> +  id = 'ArrowRightCircletIcon',
comment resolved in https://github.com/magnetis/astro-native/pull/538/commits/c88d626f3df6d91b787089916a173d70b2b52cce

2022-04-29 04:27 UTC, lucianomlima commented on src/components/Icons/utils.ts
> +}
You can create a map object that could act like a glue between a prop value and the value itself.
```suggestion
type sizeTokens = keyof typeof sizes;
 
export function getViewBox(token: sizeTokens = 'smaller') {
  return `0 0 ${sizes[token]} ${sizes[token]}`;
}

export function getSize(token: sizeTokens = 'smaller') {
  return sizes[token];
}
```

Probably this can lead to a new refactor in all icons to change size prop to a token key. If this is your case, you can do it in another PR to simplify this and isolate contexts (this PR includes new icons and new PR refactor all icons).
Maintain the retrocompatibility with the current API will be a nice plus 🌱

2022-04-29 19:53 UTC, Michele-Camargo commented on src/components/Icons/utils.ts
> +}
comment resolved in https://github.com/magnetis/astro-native/pull/538/commits/4efc4f54ee6817280e4709ae60ec68f90ffcd8fe

2022-04-29 20:04 UTC, lucianomlima approved these changes
<img src="https://media1.giphy.com/media/MQxu59c0UYzMMxjq6l/giphy.gif"/>

2022-04-29 20:05 UTC, julianosbento approved these changes
I leave some comments, but for me it's ok

2022-04-29 20:05 UTC, julianosbento commented on src/components/Icons/__tests__/utils.test.ts
> +    it('when size is diferent', () => {
```suggestion
    it('when is a custom view box', () => {
```

2022-04-29 20:05 UTC, julianosbento commented on src/components/Icons/__tests__/utils.test.ts
> +    it('when size is diferent', () => {
```suggestion
    it('when is a custom size', () => {
```

2022-04-29 20:05 UTC, julianosbento commented on src/components/Icons/utils.ts
> +type sizeTokens = keyof typeof sizes;
```suggestion
type IconSize = keyof typeof sizes;
```

2022-04-29 21:07 UTC, lucianomlima commented on src/components/Icons/utils.ts
> +type sizeTokens = keyof typeof sizes;
`sizes` aren't icon tokens only and this line allow to use all token names in the utils function below.
Because this, I think `SizeTokens` is the best name for this type.

2022-05-02 13:07 UTC, Michele-Camargo commented on src/components/Icons/utils.ts
> +type sizeTokens = keyof typeof sizes;
i agree Lu

2022-05-02 16:18 UTC, merged