[AST-57] [AST-58] [PMF-156] [PMF-155] feat(baseicon): add pressable, hitslop and size prop into icon
magnetis/astro-native pull request #70
Opened 2021-03-16 19:37 UTC by pedro-cerdera

# What
Upgrade onPress prop to icon calculating hit slop when necessary
Add prop size to icon

# Why

To be easier to manipulate and be consistent with design system

# How

Calculating histlop prop based on width and hight props (or size)
converting size prop to width and height

# Sample
<img src="https://user-images.githubusercontent.com/39625749/111368267-698b5780-8674-11eb-8958-185a640441c2.png" width="300" />

# QA

1. Run storybook locally, confirm hitSlop size with icon size lower than 48 and _onPress_ prop
2. Run storybook locally, confirm has no pressable area when icon doesn't have a _onPress_ prop
3. Run storybook locally, confirm icons width and height size when icon has a prop _size_

[AST-57](https://produtomagnetis.atlassian.net/browse/AST-57)
[AST-58](https://produtomagnetis.atlassian.net/browse/AST-58)
[PMF-155](https://produtomagnetis.atlassian.net/browse/PMF-155)
[PMF-156](https://produtomagnetis.atlassian.net/browse/PMF-156)

2021-03-16 19:45 UTC, victorheringer commented on src/components/Icons/BaseIcon.tsx
> +      <Pressable accessibilityRole="button" onPress={onPress} hitSlop={hitSlop} testID={testID}>
✨

2021-03-16 19:48 UTC, murillo94 commented on src/components/Icons/BaseIcon.tsx
> +  };
For performance reasons, wouldn't it be better to put `hitSlop` into if onPress condition? It will only render when needed.

2021-03-16 19:51 UTC, victorheringer commented on src/components/Icons/__tests__/BaseIcon.test.tsx
> +          fill="red"
So, what about we instead of using this big `d` we change it for something like `d="M16.5"`? I think if this is works, for testing purpose will be ok, if not, we could try to put this value in a single variable to prevent repetition.

2021-03-16 19:51 UTC, victorheringer submitted a review, later dismissed

2021-03-16 20:03 UTC, murillo94 submitted a review, later dismissed

2021-03-16 21:15 UTC, LopesAlysson requested changes

2021-03-16 21:15 UTC, LopesAlysson commented on src/components/Buttons/BaseButton.tsx
> +import { HitSlop } from '@components/types';
💅🏾 
```suggestion
import type { HitSlop } from '@components/types';
```

2021-03-16 21:15 UTC, LopesAlysson commented on src/components/Icons/BaseIcon.tsx
> +import { HitSlop } from '../types';
💅🏾 
```suggestion
import type { HitSlop } from '../types';
```

2021-03-16 21:15 UTC, LopesAlysson commented on src/components/Icons/BaseIcon.tsx
> +    height: size || height,
```suggestion
    width: size ?? width,
    height: size ?? height,
```

2021-03-16 21:15 UTC, LopesAlysson commented on src/components/types.ts
> +import { Insets } from 'react-native';
💅🏾 
```suggestion
import type { Insets } from 'react-native';
```

2021-03-16 21:15 UTC, LopesAlysson commented on src/components/Icons/BaseIcon.tsx
> +  onPress,
Where is this `onPress` typed? I couldn't find it on [IconProps](https://github.com/magnetis/astro-native/blob/ad4bcce470eafe94aeff1bf5dedb3d8f5c632388/src/components/Icons/types.ts) or in `BaseIconProps`;

2021-03-16 21:15 UTC, LopesAlysson commented on src/components/Icons/BaseIcon.tsx
> +    };
I can see this as a _util_ function in the future 🤔

2021-03-17 11:44 UTC, pedro-cerdera commented on src/components/Icons/BaseIcon.tsx
> +  onPress,
IconProps extends SvgProps and SvgProps contains onPress props typed

2021-03-17 13:57 UTC, LopesAlysson commented on src/components/Icons/BaseIcon.tsx
> +  onPress,
We shouldn't trust the types from this package. It's a mess, haha

And also, we use JSDoc comments to provide documentation, so it's important that every prop we use is documented, as you can see here in [IconProps](IconProps) types.

That remindes me that `size` should also be included in `IconProps` instead of `BaseIconProps`, since `IconProps` is the type accessible when using some Icon component in the lib.

2021-03-17 20:55 UTC, LopesAlysson commented on src/components/Icons/types.ts
> +  onPress?: null | ((event: GestureResponderEvent) => void);
Why can onPress be null?

2021-03-17 20:55 UTC, LopesAlysson commented on src/components/Icons/types.ts
> +  /** Size value */
I think it would be nice to mention that this prop replaces the usage of widthand height;
```suggestion
  /** Size value. This value will be used as icon's width and height internally */
```

2021-03-17 20:55 UTC, LopesAlysson commented on src/components/types.ts
> +export type HitSlop = null | Insets | number;
Why can HitSlop be null if the `getFixedHitSlop` always return an inset or a number?

2021-03-18 11:47 UTC, pedro-cerdera commented on src/components/types.ts
> +export type HitSlop = null | Insets | number;
HitSlop Type is used [here](https://github.com/magnetis/astro-native/pull/70/commits/f46fbb693109155300681254b6162116788aadb5#diff-ab29380d008d0912353c3fd4438d5ea4af9e851c8abaac5fa43fd76d8147114bR36) too. This type reflects Pressable hitslop type.

2021-03-18 13:18 UTC, LopesAlysson commented on src/components/Icons/BaseIcon.tsx
> +    const newHitSlop: HitSlop = typeof hitSlop === 'undefined' ? getFixedHitSlop(sizeProps) : hitSlop;
💅🏾 
```suggestion
    const newHitSlop: HitSlop = hitSlop ?? getFixedHitSlop(sizeProps);
```

2021-03-18 13:18 UTC, LopesAlysson commented on src/components/types.ts
> +export type HitSlop = null | Insets | number;
I can't open this link 😢 
DO you realize that because of that type, the return type of `getFixedHitSlop` is misleading? You're saying it could return a `null` value but it can't; It just returns an `Inset` or `number`.

2021-03-18 17:12 UTC, pedro-cerdera commented on src/components/Icons/BaseIcon.tsx
> +    const newHitSlop: HitSlop = typeof hitSlop === 'undefined' ? getFixedHitSlop(sizeProps) : hitSlop;
hitSlop prop could be null. In this case, we don't have to calculate hitSlop in this case.

2021-03-19 14:04 UTC, LopesAlysson submitted a review, later dismissed

2021-03-19 20:05 UTC, victorheringer approved these changes

2021-03-22 11:54 UTC, merged