feat(divider): create divider component in astro-native-next [CONFIA-1337]
magnetis/astro-native pull request #782
Opened 2023-08-11 17:53 UTC by pedrohamarques

# What

Create Divider component in astro-native-next
# Why

To follow our Design System, having our components gathered in one place that can be used in different projects.
# How

1. Creating the divider component;
2. Create story to be manipulated in the storybook.

# Sample

Storybook:

<img width="716" alt="Screenshot 2023-08-11 at 14 41 25" src="https://github.com/magnetis/astro-native/assets/35939685/e4594783-d841-4c95-8e36-055e91ee0550">

iOS:

https://github.com/magnetis/astro-native/assets/35939685/66f3e889-c246-49c0-af6f-adb3211fd063

Android:

![Screenshot_1691776288](https://github.com/magnetis/astro-native/assets/35939685/5f155666-6f77-4de1-ad5f-2debde11f580)

# QA

1. Pull the branch and run `yarn start` and `yarn storybook`;
2. Run your preferred emulator;
3. In the storybook, choose the Divider option in the side bar menu;
4. Change the properties and see if it changes in the emulator. The type on the upper divider cannot be changed, it is just for comparison.

[CONFIA-1337](https://produtomagnetis.atlassian.net/browse/CONFIA-1337)

2023-08-11 18:13 UTC, sarahrubia approved these changes

2023-08-11 18:13 UTC, sarahrubia commented on src/components/Divider/__tests__/Divider.test.tsx
> +  it('renders properly when the orientation is vertical, the type is inverse and size of 4 pixels,', () => {
💅🏾 

```suggestion
  it('renders properly when the orientation is vertical, the type is inverse and size is of 4 pixels,', () => {
```

2023-08-11 18:13 UTC, sarahrubia commented on src/components/Divider/stories/Divider.story.tsx
> +import { DividerOrientationOptions, DividerSize, DividerSizeOptions, DividerTypeOptions } from '../types';
❓ Aqui precisaria adicionar o `type`?
```suggestion
import type { DividerOrientationOptions, DividerSize, DividerSizeOptions, DividerTypeOptions } from '../types';
```

2023-08-11 18:16 UTC, pedrohamarques commented on src/components/Divider/stories/Divider.story.tsx
> +import { DividerOrientationOptions, DividerSize, DividerSizeOptions, DividerTypeOptions } from '../types';
Acredito que eu poderia dar uma ajustada, porque Os `...Options` não são types, mas arrays criados através de types que existem nesse arquivo. Já o `DividerSize` é um type mesmo.

2023-08-11 20:59 UTC, pedro-cerdera requested changes

2023-08-11 20:59 UTC, pedro-cerdera commented on src/components/Divider/Divider.tsx
> +    <View style={{ alignItems: 'center', justifyContent: 'center' }}>
❓ Is this `View` really necessary?

2023-08-11 20:59 UTC, pedro-cerdera commented on src/components/Divider/Divider.tsx
> +      <View style={{ ...baseProps }} testID={`${testID}.Line`}></View>
⛏️ 
It's very important that `testID` prop must be used explicitly. In a test case, can be used in a `getByTestId` statement
```suggestion
      <View style={{ ...baseProps }} testID={testID}></View>
```

2023-08-11 20:59 UTC, pedro-cerdera commented on src/components/Divider/__tests__/Divider.test.tsx
⛏️ 
In some of these test cases, you can pass explicitly testID as prop to test this feature

2023-08-11 21:11 UTC, lucianomlima commented on src/components/Divider/__tests__/Divider.test.tsx
> +    const { getByTestId } = render(<Divider {...initialProps} />);
⛏️ Aqui na verdade acho que deveria testar o componente sem passar nenhuma prop opcional e validar que ela carregou com o estilo correto. E com isso adicionar testes para cada prop ainda assim.

2023-08-11 21:11 UTC, lucianomlima commented on src/components/Divider/__tests__/Divider.test.tsx
> +  it('renders properly when the orientation is vertical, the type is inverse and size of 4 pixels,', () => {
Eu diria que deveria mudar a parte do size para ter o valor que passamos não o valor que é atribuído no estilo
```suggestion
  it('renders properly when the orientation is vertical, the type is inverse and size is thick,', () => {
```

2023-08-14 12:55 UTC, pedrohamarques commented on src/components/Divider/types.ts
> +export const DividerSizeOptions = [...Object.keys(borders)] as const;
Yes, but the purpose here is to make it `readonly` also, to keep the pattern with the other options.

2023-08-14 12:58 UTC, pedrohamarques commented on src/components/Divider/__tests__/Divider.test.tsx
> +const initialProps: DividerProps = {
I tried to doesn't use it. But TS didn`t infer it.

2023-08-14 13:07 UTC, pedrohamarques commented on src/components/Divider/stories/Divider.story.tsx
> +        type={select('type', DividerTypeOptions, DividerTypeOptions[0])}
It's to allow the user to know that there is this prop and has the possibility to change it.

2023-08-14 13:11 UTC, pedrohamarques commented on src/components/Divider/stories/Divider.story.tsx
> +    <View style={{ ...styles.view, backgroundColor: colors.solidFaintDarker }}>
Good to know! But i think in this situation it shouldn't work because this add-on changes the entire background, no?

2023-08-14 17:39 UTC, lucianomlima commented on src/components/Divider/Divider.tsx
> +    <View style={{ alignItems: 'center', justifyContent: 'center' }}>
💡 Maybe you shoud create a styles object to put this props.

2023-08-14 17:41 UTC, lucianomlima commented on src/components/Divider/types.ts
> +export const DividerSizeOptions = [...Object.keys(borders)] as const;
But in my suggestion `as const` is not removed, continues to be readonly no?

2023-08-14 17:42 UTC, pedrohamarques commented on src/components/Divider/__tests__/Divider.test.tsx
> +    const { getByTestId } = render(<Divider {...initialProps} />);
Fixed in [61de2ac](https://github.com/magnetis/astro-native/pull/782/commits/61de2acb8a0d6e0340f134e916e88bc4e2aa5242)

2023-08-14 17:44 UTC, pedrohamarques commented on src/components/Divider/__tests__/Divider.test.tsx
Fixed in [61de2ac](https://github.com/magnetis/astro-native/pull/782/commits/61de2acb8a0d6e0340f134e916e88bc4e2aa5242)

2023-08-14 17:44 UTC, pedrohamarques commented on src/components/Divider/Divider.tsx
> +      <View style={{ ...baseProps }} testID={`${testID}.Line`}></View>
Fixed in [61de2ac](https://github.com/magnetis/astro-native/pull/782/commits/61de2acb8a0d6e0340f134e916e88bc4e2aa5242)

2023-08-14 17:45 UTC, pedrohamarques commented on src/components/Divider/Divider.tsx
> +    <View style={{ alignItems: 'center', justifyContent: 'center' }}>
With just one prop? I fixed and it only needs the alignItems property

2023-08-14 17:45 UTC, pedrohamarques commented on src/components/Divider/stories/Divider.story.tsx
> +import { DividerOrientationOptions, DividerSize, DividerSizeOptions, DividerTypeOptions } from '../types';
Fixed in [61de2ac](https://github.com/magnetis/astro-native/pull/782/commits/61de2acb8a0d6e0340f134e916e88bc4e2aa5242)

2023-08-14 17:45 UTC, pedrohamarques commented on src/components/Divider/__tests__/Divider.test.tsx
> +  it('renders properly when the orientation is vertical, the type is inverse and size of 4 pixels,', () => {
Fixed in [61de2ac](https://github.com/magnetis/astro-native/pull/782/commits/61de2acb8a0d6e0340f134e916e88bc4e2aa5242)

2023-08-14 17:46 UTC, lucianomlima commented on src/components/Divider/stories/Divider.story.tsx
> +        type={select('type', DividerTypeOptions, DividerTypeOptions[0])}
But it keeps the same background, not helping in the validation when selecting the other option. Since there are only two options, it seems unnecessary.

2023-08-14 17:51 UTC, lucianomlima commented on src/components/Divider/stories/Divider.story.tsx
> +    <View style={{ ...styles.view, backgroundColor: colors.solidFaintDarker }}>
Yes and I think it's the expected behavior, allowing to see the component with the best background color for some options, also helping to avoid hardcoded options. But it's not a requirement for this PR, only a future idea.

2023-08-14 18:03 UTC, lucianomlima commented on src/components/Divider/Divider.tsx
> +    <View style={{ alignItems: 'center', justifyContent: 'center' }}>
Yes, this is an eslint config setup issue for this project. We always avoid adding inline styles and should avoid creating new components with inline styles.
May need to create a technical debit card to resolve this sometime in the future

2023-08-14 18:07 UTC, lucianomlima commented on src/components/Divider/__tests__/Divider.test.tsx
> +    expect(getByTestId('divider.line')).toHaveStyle({
🔧 What Cerdeira meant is that you should test with another testID to make sure it can be used in the app.

2023-08-14 18:09 UTC, pedrohamarques commented on src/components/Divider/__tests__/Divider.test.tsx
> +    expect(getByTestId('divider.line')).toHaveStyle({
That's what I did. The default value is `Divider`. I passed to the prop the value `divider.line` and it worked.

2023-08-14 18:09 UTC, lucianomlima commented on src/components/Divider/__tests__/Divider.test.tsx
> +    const { getByTestId } = render(<Divider {...initialProps} />);
There is not a test for each prop and its values.

2023-08-14 18:14 UTC, lucianomlima commented on src/components/Divider/stories/Divider.story.tsx
> +import { DividerOrientationOptions, DividerSize, DividerSizeOptions, DividerTypeOptions } from '../types';
I don't see the contants.ts file

2023-08-14 18:18 UTC, lucianomlima commented on src/components/Divider/__tests__/Divider.test.tsx
> +    expect(getByTestId('divider.line')).toHaveStyle({
Weird, for me it wasn't showing as `Divider` but I updated it here and it showed.

2023-08-14 18:24 UTC, lucianomlima approved these changes
LGTM besides the comment related to the tests

2023-08-14 18:25 UTC, pedrohamarques commented on src/components/Divider/Divider.tsx
> +    <View style={{ alignItems: 'center', justifyContent: 'center' }}>
Card created:  https://produtomagnetis.atlassian.net/browse/CONFIA-1342

2023-08-14 19:10 UTC, pedrohamarques commented on src/components/Divider/__tests__/Divider.test.tsx
> +    const { getByTestId } = render(<Divider {...initialProps} />);
Fixed in [076a805](https://github.com/magnetis/astro-native/pull/782/commits/076a805c58d0a444b1934c257b5d1643e04cb5df)

2023-08-14 20:18 UTC, lucianomlima commented on src/components/Divider/constants.ts
🤔 Faz sentido testar constantes? Afinal elas não são dinâmicas. Seus valores serão os mesmos sempre (exceto quando mudarem).

2023-08-14 20:21 UTC, pedrohamarques commented on src/components/Divider/constants.ts
O CI exigiu. Não passou na primeira vez porque não tinha testes para esse arquivo, precisei criar

2023-08-14 20:30 UTC, lucianomlima commented on src/components/Divider/constants.ts
Here the fix is to ignore the constants file in jest.config file:
https://github.com/magnetis/astro-native/blob/e6ea5baa8397ca55675e85161f9ad573dddb25d5/jest.config.js#L7-L12

Can be done adding `contants.ts` in the collectCoverageFrom jest configuration.

2023-08-14 20:40 UTC, pedrohamarques commented on src/components/Divider/constants.ts
Fixed in [dfd1e91](https://github.com/magnetis/astro-native/pull/782/commits/dfd1e912650f2218ac2e27bdf7400ec766587501)

2023-08-15 19:42 UTC, sarahrubia commented on src/components/Divider/Divider.tsx
>   * @param {DividerType} props.type - The type of the DIvider.
💅🏾 
```suggestion
 * @param {DividerType} props.type - The type of the Divider.
 ```

2023-08-15 19:44 UTC, sarahrubia approved these changes

2023-08-16 12:39 UTC, pedrohamarques commented on src/components/Divider/Divider.tsx
>   * @param {DividerType} props.type - The type of the DIvider.
Fixed in [9032dd3](https://github.com/magnetis/astro-native/pull/782/commits/9032dd32f822f37bb733aa7d842fc270f6343c58)

2023-08-16 13:40 UTC, merged